//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------
#nullable disable

namespace ContextMenuManager.Properties
{
    using System;
    using System.Globalization;
    using System.Resources;

    /// <summary>Strongly-typed access to UI strings. Culture is set at app startup.</summary>
    public static class Resources
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (_resourceMan == null)
                {
                    var temp = new ResourceManager("ContextMenuManager.Properties.Resources", typeof(Resources).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        /// <summary>Current culture for resource lookups. Null = use CurrentUICulture.</summary>
        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        private static string GetString(string name) =>
            ResourceManager.GetString(name, _resourceCulture ?? CultureInfo.CurrentUICulture) ?? name;

        private static string GetString(string name, params object[] args)
        {
            var fmt = ResourceManager.GetString(name, _resourceCulture ?? CultureInfo.CurrentUICulture);
            return string.IsNullOrEmpty(fmt) ? name : string.Format(fmt, args);
        }

        public static string WindowTitle => GetString("WindowTitle");
        public static string Subtitle => GetString("Subtitle");
        public static string MenuModeLabel => GetString("MenuModeLabel");
        public static string Win11New => GetString("Win11New");
        public static string Win10Classic => GetString("Win10Classic");
        public static string LanguageLabel => GetString("LanguageLabel");
        public static string LanguageRestartHint => GetString("LanguageRestartHint");
        public static string SearchPlaceholder => GetString("SearchPlaceholder");
        public static string Scenario_File => GetString("Scenario_File");
        public static string Scenario_Directory => GetString("Scenario_Directory");
        public static string Scenario_DirectoryBackground => GetString("Scenario_DirectoryBackground");
        public static string Scenario_DesktopBackground => GetString("Scenario_DesktopBackground");
        public static string ItemsCountSuffix => GetString("ItemsCountSuffix");
        public static string TooltipHasChanges => GetString("TooltipHasChanges");
        public static string Loading => GetString("Loading");
        public static string NoItemsFound => GetString("NoItemsFound");
        public static string NoItemsHint => GetString("NoItemsHint");
        public static string ButtonRefresh => GetString("ButtonRefresh");
        public static string ButtonSync => GetString("ButtonSync");
        public static string ButtonBackup => GetString("ButtonBackup");
        public static string RestoreLastBackup => GetString("RestoreLastBackup");
        public static string RestoreDefault => GetString("RestoreDefault");
        public static string OpenBackupFolder => GetString("OpenBackupFolder");
        public static string RestartExplorer => GetString("RestartExplorer");
        public static string TooltipRestartExplorer => GetString("TooltipRestartExplorer");
        public static string ApplyChanges => GetString("ApplyChanges");
        public static string HintRestartExplorer => GetString("HintRestartExplorer");
        public static string Scope_CurrentUser => GetString("Scope_CurrentUser");
        public static string Scope_AllUsers => GetString("Scope_AllUsers");
        public static string Scenario_Unknown => GetString("Scenario_Unknown");
        public static string Source_System => GetString("Source_System");
        public static string Source_ThirdParty => GetString("Source_ThirdParty");
        public static string Source_Unknown => GetString("Source_Unknown");
        public static string Risk_Low => GetString("Risk_Low");
        public static string Risk_Medium => GetString("Risk_Medium");
        public static string Risk_High => GetString("Risk_High");
        public static string Risk_Unknown => GetString("Risk_Unknown");
        public static string ItemType_Command => GetString("ItemType_Command");
        public static string ItemType_Extension => GetString("ItemType_Extension");
        public static string ItemType_Unknown => GetString("ItemType_Unknown");
        public static string Status_Scanning => GetString("Status_Scanning");
        public static string Status_Loaded => GetString("Status_Loaded");
        public static string Status_LoadFailed => GetString("Status_LoadFailed");
        public static string Status_NoChanges => GetString("Status_NoChanges");
        public static string Status_Applying => GetString("Status_Applying");
        public static string Status_ApplySuccess => GetString("Status_ApplySuccess");
        public static string Status_ApplyPartial => GetString("Status_ApplyPartial");
        public static string Status_ApplyFailed => GetString("Status_ApplyFailed");
        public static string Status_Restoring => GetString("Status_Restoring");
        public static string Status_Restored => GetString("Status_Restored");
        public static string Status_RestoreFailed => GetString("Status_RestoreFailed");
        public static string Status_Resetting => GetString("Status_Resetting");
        public static string Status_ResetDone => GetString("Status_ResetDone");
        public static string Status_ResetFailed => GetString("Status_ResetFailed");
        public static string Status_ClassicOn => GetString("Status_ClassicOn");
        public static string Status_ClassicOff => GetString("Status_ClassicOff");
        public static string Status_ClassicFailed => GetString("Status_ClassicFailed");
        public static string Status_ExplorerRestarted => GetString("Status_ExplorerRestarted");
        public static string Status_ExplorerFailed => GetString("Status_ExplorerFailed");
        public static string Msg_AdminRequired => GetString("Msg_AdminRequired");
        public static string Msg_AdminRequiredTitle => GetString("Msg_AdminRequiredTitle");
        public static string Msg_ApplyPartial => GetString("Msg_ApplyPartial");
        public static string Msg_ApplyPartialTitle => GetString("Msg_ApplyPartialTitle");
        public static string Msg_NoBackup => GetString("Msg_NoBackup");
        public static string Msg_NoBackupTitle => GetString("Msg_NoBackupTitle");
        public static string Msg_ConfirmRestore => GetString("Msg_ConfirmRestore");
        public static string Msg_ConfirmRestoreTitle => GetString("Msg_ConfirmRestoreTitle");
        public static string Msg_ConfirmReset => GetString("Msg_ConfirmReset");
        public static string Msg_ConfirmResetTitle => GetString("Msg_ConfirmResetTitle");
        public static string Msg_ClassicRestart => GetString("Msg_ClassicRestart");
        public static string Msg_ClassicRestartTitle => GetString("Msg_ClassicRestartTitle");
        public static string Msg_ClassicError => GetString("Msg_ClassicError");
        public static string Msg_ClassicErrorTitle => GetString("Msg_ClassicErrorTitle");
        public static string Msg_ExplorerConfirm => GetString("Msg_ExplorerConfirm");
        public static string Msg_ExplorerConfirmTitle => GetString("Msg_ExplorerConfirmTitle");
        public static string SyncDialogTitle => GetString("SyncDialogTitle");
        public static string SyncDialogIntro => GetString("SyncDialogIntro");
        public static string SyncToDirectory => GetString("SyncToDirectory");
        public static string SyncToDirectoryBg => GetString("SyncToDirectoryBg");
        public static string SyncToDesktopBg => GetString("SyncToDesktopBg");
        public static string OK => GetString("OK");
        public static string Cancel => GetString("Cancel");
        public static string SyncSelectOne => GetString("SyncSelectOne");
        public static string SyncSelectOneTitle => GetString("SyncSelectOneTitle");
        public static string SyncResultOk => GetString("SyncResultOk");
        public static string SyncResultNone => GetString("SyncResultNone");
        public static string SyncResultTitle => GetString("SyncResultTitle");

        public static string Format(string key, params object[] args) => GetString(key, args);
    }
}
